# Generated by Django 3.1.7 on 2021-03-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='core/product/default.jpg', upload_to='core/product/'),
        ),
    ]
